last_id: 59
models: 
  54: # previously trained models are deleted for clarity
    additional_note: FINAL MODEL - used model, best performance so far
    area_thresholds:
    - '0.00936291'
    - '0.05047598'
    - '0.00442774'
    - '0.00321187'
    - '0.00172695'
    - '0.02882062'
    - '0.58099972'
    - '0.09412956'
    - '0.00120491'
    area_thresholds_old_traces:
    - '0.66765500'
    - '3.08736465'
    - '0.00317315'
    - '0.00130149'
    - '0.00518348'
    - '0.01924304'
    - '0.23818347'
    - '0.03699150'
    - '0.01120571'
    batch_size: 128
    best_epoch: 5
    description: finalised training configuration
    epochs: 100
    evaluation_window_size: 200
    model_id: 54
    multistep: 1
    sigma_rule: 4
    signal_groups:
      1:
        signals:
        - '0110_0'
        - '0120_3'
        units: 64
      2:
        signals:
        - '0110_1'
        - '0110_3'
        - '0120_0'
        - '0120_1'
        units: 64
      3:
        signals:
        - '0120_2'
        units: 64
      4:
        signals:
        - 0381_4
        units: 64
      5:
        signals:
        - 0280_0
        - 0280_1
        - 0280_2
        - 0280_3
        - '0410_0'
        units: 64
      6:
        signals:
        - 0290_0
        units: 64
      7:
        signals:
        - 0290_4
        - 0290_2
        units: 64
      8:
        signals:
        - 0290_1
        - '0410_4'
        units: 64
      9:
        signals:
        - '0300_4'
        - 0381_6
        units: 64
    stride: 1
    time_of_training: 2023.09.27_02:15_
    train_folder: train/train_input
    trained_on: '80% train, 20% validation: [''_work_dir/train/train_input/T-1-4-benign.log'',
      ''_work_dir/train/train_input/T-1-2-benign.log'',
      ''_work_dir/train/train_input/T-1-5-benign.log'',
      ''_work_dir/train/train_input/T-1-3-benign.log'',
      ''_work_dir/train/train_input/T-1-1-benign.log'']'
    type: Grouped multi-signal TCN
    window_size: 1750